Move test-compat-table out of make test.
Remove the git url in the package.json and put it in the make rule.
The automatic test force network access on every make test and
added more dependencies than value we got from automatic testing.
(The current data file from compat-table fails in V8 due to
SyntaxError: Duplicate data property in object literal not allowed in strict mode

Review URL: https://api.github.com/repos/google/traceur-compiler/issues/1501

Closes #1501.